// Loads data/<lang>/lessons.json into the lessons tables.
//
//     npm run db:lessons [-- --lang ka] [-- --force] [-- --lesson <id>]
//
// The one importer in this repo whose default is to *skip* what is already there. Every other
// loader upserts, because the file it reads is generated and the database is a copy of it. This
// file is not generated by anything: data/ka/lessons.json was written once, by
// scripts/lessonsFromGrammar.ts converting the grammar module that the lessons replaced, and
// from that moment the database is where lessons are edited and the file is a snapshot of how
// they started.
//
// So a lesson whose id is already in the table is left exactly as it stands, and the run says
// how many it passed over. `--force` is how you say the file is right and whatever was done in
// the browser is not — which is a thing you would occasionally mean, and never by accident. It
// takes `--lesson <id>` beside it, which is how you mean that about one lesson rather than
// about every lesson in the file.
//
// Nothing here deletes. A lesson written in the admin screens and absent from the file is not
// something this knows about, which is the correct reading of a file that says what exists
// rather than what has stopped existing.

import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { eq, sql as raw } from 'drizzle-orm';
import { isLang, type Lang } from '@georgian/shared/grammar';
import { isLessonSection, isQuizKind, type LessonSection } from '@georgian/shared/types';
import { db, schema, sql } from './index.ts';

const DATA = fileURLToPath(new URL('../../../../data/', import.meta.url));

interface LessonFileCategory {
  id: string;
  section: string;
  name: string;
  nameNative?: string;
  note?: string;
}

interface LessonFileLesson {
  id: string;
  section: string;
  title: string;
  titleNative?: string;
  summary?: string;
  level?: string;
  categoryId?: string | null;
  body: string;
  note?: string;
}

/**
 * A quiz, in the same file as the lessons that embed it.
 *
 * There has never been a file behind the quizzes — the note at the head of schema.ts says so,
 * and it was true: a quiz was written in the admin screens and nowhere else. This is not that
 * changing. It is the observation that a starter lesson ending in `::quiz first-letters` is not
 * a lesson unless that quiz exists, so shipping the lessons without the quizzes would ship
 * fifteen pages with holes in them. They travel together because they are one thing.
 *
 * Quizzes written afterwards in the admin screens are still written there and are still in no
 * file. This loader adds; it never exports and never deletes.
 */
interface LessonFileQuiz {
  id: string;
  title: string;
  titleNative?: string;
  description?: string;
  level?: string;
  categoryId?: string | null;
  passMark?: number;
  shuffleQuestions?: boolean;
  shuffleOptions?: boolean;
  /** Ask this many at random. Omitted or 0 asks the lot. */
  askCount?: number;
  questions: {
    kind: string;
    prompt?: string;
    promptNative?: string;
    /** What a voice reads for the prompt. The starter quizzes use this rather than uploads. */
    say?: string;
    multiple?: boolean;
    /** `type` questions only: every spelling that counts. */
    answers?: string[];
    hint?: string;
    explanation?: string;
    choices?: { text?: string; correct?: boolean; say?: string }[];
  }[];
}

interface LessonFile {
  note?: string;
  lang?: string;
  categories: LessonFileCategory[];
  lessons: LessonFileLesson[];
  quizCategories?: LessonFileCategory[];
  quizzes?: LessonFileQuiz[];
}

/* --------------------------------------------------------------------- args */

const args = process.argv.slice(2);
const force = args.includes('--force');
const at = args.indexOf('--lang');
const asked = at === -1 ? null : args[at + 1] ?? '';

/**
 * One lesson rather than the file, for the run that means to overwrite something.
 *
 * `--force` on its own is the whole file, which is right after editing lessons.json by hand and
 * wrong for every other reason to reach for it: a lesson whose text has changed in the repo
 * still sits beside twenty that have been edited in the admin screens since, and there is no
 * version of "load the new one" that should also flatten those. Paired with `--force`, this is
 * that version.
 */
const lessonAt = args.indexOf('--lesson');
const justLesson = lessonAt === -1 ? null : args[lessonAt + 1] ?? '';

if (justLesson === '') {
  console.error('--lesson wants the id of a lesson, as it appears in lessons.json.');
  process.exit(1);
}

if (asked !== null && !isLang(asked)) {
  console.error(`“${asked}” is not a language this build knows about.`);
  process.exit(1);
}

// `process.exit` above makes this safe, and the narrowing has to be written out because
// TypeScript does not know that a call which never returns ends the branch.
const only = asked as Lang | null;

/* -------------------------------------------------------------------- work */

/**
 * The next free position, so imported rows land after anything already filed.
 *
 * Takes the transaction rather than reaching for `db`, and that is not tidiness: the rows this
 * has to count are the ones inserted a moment ago by the same loop, and they are not visible
 * outside the transaction that is inserting them. Asked through `db` it answers the same number
 * every time, and a whole file imports at position 0 — a list in whatever order Postgres feels
 * like returning it.
 */
async function nextPosition(
  tx: Parameters<Parameters<typeof db.transaction>[0]>[0],
  table:
    | typeof schema.lessons
    | typeof schema.lessonCategories
    | typeof schema.quizzes
    | typeof schema.quizCategories,
): Promise<number> {
  const [row] = await tx.select({ max: raw<number | null>`max(${table.position})` }).from(table);
  return (row?.max ?? -1) + 1;
}

function section(value: string, what: string): LessonSection {
  if (!isLessonSection(value)) throw new Error(`${what} is in section “${value}”, which is not one.`);
  return value;
}

async function load(lang: Lang): Promise<void> {
  const path = `${DATA}${lang}/lessons.json`;
  if (!existsSync(path)) {
    console.log(`${lang}: no lessons.json, nothing to do.`);
    return;
  }

  const file = JSON.parse(readFileSync(path, 'utf-8')) as LessonFile;
  let addedCategories = 0;
  let addedLessons = 0;
  let skipped = 0;
  let replaced = 0;
  let addedQuizzes = 0;
  let skippedQuizzes = 0;
  let addedQuizCategories = 0;

  await db.transaction(async tx => {
    for (const category of file.categories) {
      const [existing] = await tx
        .select({ id: schema.lessonCategories.id })
        .from(schema.lessonCategories)
        .where(eq(schema.lessonCategories.id, category.id))
        .limit(1);

      const row = {
        lang,
        section: section(category.section, `Category ${category.id}`),
        name: category.name,
        nameNative: category.nameNative ?? '',
        note: category.note ?? '',
      };

      if (!existing) {
        await tx
          .insert(schema.lessonCategories)
          .values({ ...row, id: category.id, position: await nextPosition(tx, schema.lessonCategories) });
        addedCategories += 1;
      } else if (force && !justLesson) {
        await tx.update(schema.lessonCategories).set(row).where(eq(schema.lessonCategories.id, category.id));
      }
    }

    for (const lesson of file.lessons) {
      if (justLesson && lesson.id !== justLesson) continue;

      const [existing] = await tx
        .select({ id: schema.lessons.id })
        .from(schema.lessons)
        .where(eq(schema.lessons.id, lesson.id))
        .limit(1);

      if (existing && !force) {
        skipped += 1;
        continue;
      }

      const row = {
        lang,
        section: section(lesson.section, `Lesson ${lesson.id}`),
        title: lesson.title,
        titleNative: lesson.titleNative ?? '',
        summary: lesson.summary ?? '',
        level: lesson.level ?? '',
        categoryId: lesson.categoryId ?? null,
        body: lesson.body,
        note: lesson.note ?? '',
      };

      if (existing) {
        await tx.update(schema.lessons).set(row).where(eq(schema.lessons.id, lesson.id));
        replaced += 1;
      } else {
        await tx.insert(schema.lessons).values({ ...row, id: lesson.id, position: await nextPosition(tx, schema.lessons) });
        addedLessons += 1;
      }
    }

    /* -- the quizzes those lessons embed -- */

    for (const category of file.quizCategories ?? []) {
      const [existing] = await tx
        .select({ id: schema.quizCategories.id })
        .from(schema.quizCategories)
        .where(eq(schema.quizCategories.id, category.id))
        .limit(1);
      // `--lesson` narrows a forced run to the one lesson named. A quiz or a shelf it embeds is
      // still created where it is missing — a lesson whose quiz does not exist is a page with a
      // hole in it — but nothing already in the database is rewritten.
      if (existing && (!force || justLesson)) continue;

      const row = { lang, name: category.name, nameNative: category.nameNative ?? '', note: category.note ?? '' };
      if (existing) {
        await tx.update(schema.quizCategories).set(row).where(eq(schema.quizCategories.id, category.id));
      } else {
        await tx
          .insert(schema.quizCategories)
          .values({ ...row, id: category.id, position: await nextPosition(tx, schema.quizCategories) });
        addedQuizCategories += 1;
      }
    }

    for (const quiz of file.quizzes ?? []) {
      const [existing] = await tx
        .select({ id: schema.quizzes.id })
        .from(schema.quizzes)
        .where(eq(schema.quizzes.id, quiz.id))
        .limit(1);

      if (existing && (!force || justLesson)) {
        skippedQuizzes += 1;
        continue;
      }

      for (const [at, question] of quiz.questions.entries()) {
        if (!isQuizKind(question.kind)) {
          throw new Error(`Quiz ${quiz.id}, question ${at + 1}: “${question.kind}” is not a kind of question.`);
        }
      }

      const row = {
        lang,
        title: quiz.title,
        titleNative: quiz.titleNative ?? '',
        description: quiz.description ?? '',
        level: quiz.level ?? '',
        categoryId: quiz.categoryId ?? null,
        shuffleQuestions: quiz.shuffleQuestions ?? true,
        shuffleOptions: quiz.shuffleOptions ?? true,
        askCount: quiz.askCount ?? 0,
        passMark: quiz.passMark ?? 70,
        questionCount: quiz.questions.length,
        note: '',
      };

      if (existing) {
        await tx.update(schema.quizzes).set(row).where(eq(schema.quizzes.id, quiz.id));
      } else {
        await tx.insert(schema.quizzes).values({ ...row, id: quiz.id, position: await nextPosition(tx, schema.quizzes) });
        addedQuizzes += 1;
      }

      // Out with all of them, in with all of them — the rule `writeQuiz` follows, and for the
      // reason given there: a question's identity is its position, so there is nothing to diff
      // against and no state where the questions and their options disagree about how many
      // there are.
      await tx.delete(schema.quizChoices).where(eq(schema.quizChoices.quizId, quiz.id));
      await tx.delete(schema.quizQuestions).where(eq(schema.quizQuestions.quizId, quiz.id));

      await tx.insert(schema.quizQuestions).values(
        quiz.questions.map((question, position) => ({
          quizId: quiz.id,
          position,
          kind: question.kind,
          prompt: question.prompt ?? '',
          promptNative: question.promptNative ?? '',
          say: question.say ?? '',
          multiple: question.multiple ?? false,
          answers: question.kind === 'type' ? question.answers ?? [] : [],
          hint: question.hint ?? '',
          explanation: question.explanation ?? '',
        })),
      );

      const choices = quiz.questions.flatMap((question, at) =>
        question.kind === 'type'
          ? []
          : (question.choices ?? []).map((choice, position) => ({
              quizId: quiz.id,
              question: at,
              position,
              text: choice.text ?? '',
              correct: choice.correct ?? false,
              say: choice.say ?? '',
            })),
      );
      if (choices.length) await tx.insert(schema.quizChoices).values(choices);
    }

    for (const category of file.quizCategories ?? []) {
      const [count] = await tx
        .select({ total: raw<number>`count(*)` })
        .from(schema.quizzes)
        .where(eq(schema.quizzes.categoryId, category.id));
      await tx
        .update(schema.quizCategories)
        .set({ quizCount: Number(count?.total ?? 0) })
        .where(eq(schema.quizCategories.id, category.id));
    }

    // The counts the index draws, recomputed rather than trusted from the file — the file has
    // no idea what else is already filed on these shelves.
    for (const category of file.categories) {
      const [count] = await tx
        .select({ total: raw<number>`count(*)` })
        .from(schema.lessons)
        .where(eq(schema.lessons.categoryId, category.id));
      await tx
        .update(schema.lessonCategories)
        .set({ lessonCount: Number(count?.total ?? 0) })
        .where(eq(schema.lessonCategories.id, category.id));
    }

    // Last, in the same transaction, exactly as an edit made in the browser does it: the
    // server's snapshot is keyed on this and so is every reader's cached copy.
    const version = Math.random().toString(36).slice(2, 18);
    await tx
      .insert(schema.contentVersion)
      .values({ lang, version, source: 'admin', builtAt: new Date() })
      .onConflictDoUpdate({
        target: schema.contentVersion.lang,
        set: { version, source: 'admin', builtAt: new Date() },
      });
  });

  console.log(
    `${lang}: ${addedLessons} lessons added, ${replaced} replaced, ${skipped} left alone, ` +
      `${addedCategories} categories added.`,
  );
  if (addedQuizzes || skippedQuizzes || addedQuizCategories) {
    console.log(
      `${lang}: ${addedQuizzes} quizzes added, ${skippedQuizzes} left alone, ` +
        `${addedQuizCategories} quiz categories added.`,
    );
  }
  if (skipped && !force) {
    console.log('  Those already exist. Pass --force to overwrite them with what is in the file.');
  }
}

for (const lang of only ? [only] : (['ka', 'ru'] as const)) {
  await load(lang);
}

await sql.end({ timeout: 5 });
